//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string E_Mail { get; set; }
        public string Department { get; set; }
        public string Password { get; set; }
        public bool E_MailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}
